# This manifest defines a Kustomization resource for Flux CD to manage application deployments
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps  # Identifier for this Kustomization
  namespace: flux-system  # Namespace where this resource lives
spec:
  # How often Flux should reconcile this Kustomization
  interval: 10m
  
  # Maximum time to wait for resource operations to complete
  timeout: 5m
  
  # dependsOn:
  # - name: infra-configs
  
  # Path to the directory containing Kustomize overlays and resources
  path: ./apps/staging
  
  # Enable garbage collection - remove resources that are no longer present in Git
  prune: true
  
  # Reference to the Git repo containing the Kustomize files that Flux should apply for the cluster
  sourceRef:
    kind: GitRepository
    name: flux-system