# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: linkding
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Recycle
#   storageClassName: manual
#   hostPath:
#     path: "/mnt/data"


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi